### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by pthariensflame** [roelvandijk/containers-unicode-symbols#5]
Same comment as on roelvandijk/base-unicode-symbols#16; there are commits in this repo that aren't on Hackage yet, despite them being [almost two years old](https://hackage.haskell.org/package/containers-unicode-symbols-0.3.1.1).

**Comment by oblitum** [comment]
Just mailed maintainer of base-unicode-symbols on Arch Linux and he said containers-unicode-symbols isn't being provided in their repos for lack of a release post 2013.

**Comment by pthariensflame** [comment]
D:

**Comment by roelvandijk** [comment]
I released http://hackage.haskell.org/package/containers-unicode-symbols-0.3.1.2. It supports the newest containers release.
