### ISSUE TITLE
containers-unicode-symbols does not support the latest version of containers

### ISSUE THREAD

**Issue by EvanMisshula** [roelvandijk/containers-unicode-symbols#8]
The latest version of containers since June 18 of 2018 is 0.6.0.1.  This repo only support versions less than 0.6. Nixos makes this even more critical since containers is considered a base package and the only way to drop versions is to drop versions of the ghc compiler. The program:
``` bash
cabal2nix --jailbreak --no-check 
```
also fails because jailbreak does not work on cabal if statements. A simple change to the cabal file makes the minimal change to cure this problem.  I am going to submit an associated pull request.

**Comment by roelvandijk** [comment]
Thanks for the pull request!
